pams_panel_x/config/routes.rb
Rails.application.routes.draw do
 

     devise_for :users

 


  get 'landing/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        root 'landing#index'
 scope	":locale" do
        resources :instructors do
		end

		resources :students do
		end

		resources :courses do
		end

		resources :cohorts do
		end

 end
end

pams_panel_x/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pams_panel_x/app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
  validates :name, :start_date, :end_date,:course_id, :instructor_id, presence: true

end

pams_panel_x/app/models/course.rb
class Course < ApplicationRecord
	validates :name, :total_in_class_hours, presence: true
   validates :total_in_class_hours, numericality: { :greater_than => 0}
end

pams_panel_x/app/models/instructor.rb
class Instructor < ApplicationRecord
	validates :first_name, :last_name, :age, :salary, :highest_completed_education, presence: true
	validates :salary, numericality: { :greater_than => 0}
	validates :age, numericality: { :less_than => 150}

end

pams_panel_x/app/models/student.rb
class Student < ApplicationRecord
	validates :first_name, :last_name, :age, :highest_completed_education, presence: true
	validates :age, numericality: { :less_than => 150}
end

pams_panel_x/app/models/students_cohort.rb
class StudentsCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

pams_panel_x/app/models/user.rb
class User < ApplicationRecord

 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

pams_panel_x/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_locale

	private

	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
		
	end

	def default_url_options
		{locale: I18n.locale}
		
	end
		
end

pams_panel_x/app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
    before_action :authenticate_user!
	def index
		@cohorts = Cohort.all	
	end

	def create
		Cohort.create(cohort_params)
		@instructors = Instructor.all
		@courses = Course.all

		flash[:notice] = "New Cohort Record created Successfully!"

		redirect_to  cohorts_path
	end

	def new
		@cohort = Cohort.new
		@instructors = Instructor.all
		@courses = Course.all
	end

	def edit
		@cohort = Cohort.find(params[:id])
		@instructors = Instructor.all
		@courses = Course.all
	end 

	def show
		@cohort = Cohort.find(params[:id])
	end

	def update
		cohort = Cohort.find(params[:id])
		cohort.update(cohort_params)

		@instructors = Instructor.all
		@courses = Course.all

		flash[:notice] = "Updated Successfully!"

		redirect_to cohorts_path
	end

	def destroy
		Cohort.destroy(params[:id])
		redirect_to cohorts_path
	end

	private	

	def cohort_params
		params.require(:cohort).permit(:name, :start_date, :end_date, :course_id, :instructor_id)
		
	end
end

pams_panel_x/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user!
	def index
		@courses = Course.all	
	end

	def create
		@course = Course.create(course_params)
		if @course.valid?
		    flash[:notice] = "Success! New Course Record Made."
		     redirect_to courses_path
		 else
		 	flash[:notice] = "Missing Information."
		 	render :new
		 end

	def new
		@course = Course.new
	end

	def edit
		@course = Course.find(params[:id])
	end 

	def show
		@course = Course.find(params[:id])
	end

	def update
		course = Course.find(params[:id])
		course.update(course_params)
		flash[:notice] = "Updated Successfully!"

		redirect_to courses_path
	end

	def destroy
		Course.destroy(params[:id])
		redirect_to courses_path
	end

	private	

	def course_params
		params.require(:course).permit(:name, :total_in_class_hours)
		
	end
end
end

pams_panel_x/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	before_action :authenticate_user!
	def index
		@instructors = Instructor.all
	end


	def create
		@instructor = Instructor.create(instructor_params)

		if @instructor.valid?
		    flash[:notice] = "Success! New Instructor Record Made."
		     redirect_to instructors_path
		 else
		 	flash[:notice] = "Missing Information."
		 	render :new
		 end
	end

	def new
		@instructor = Instructor.new	
	end

	def edit
		@instructor = Instructor.find(params[:id])
	end

	def show
		@instructor = Instructor.find(params[:id])
	end

	def update
		instructor = Instructor.find(params[:id])
		instructor.update(instructor_params)
		flash[:notice] = "Record Updated Successfully!"
		
		redirect_to instructors_path
	end

	def destroy
		# find a way to hide instead of destroy teacher data.
		Instructor.destroy(params[:id])
		redirect_to instructors_path
	end

	def instructor_params
		params.require(:instructor).permit(:first_name, :last_name, :highest_completed_education, :age, :salary)
		
	end
end

pams_panel_x/app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

pams_panel_x/app/controllers/students_cohorts_controller.rb
class StudentsCohortsController < ApplicationController
	
end

pams_panel_x/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!
	def index
		@students = Student.all.order(:last_name)
	end

	def create
		@student = Student.create(student_params)
        
        if @student.valid?
		    flash[:notice] = t('notice.new')
		     redirect_to students_path
		 else
		 	flash[:notice] = t('notice.failure')
		 	render :new
		 end
	end

	def new
		@student = Student.new
	end

	def edit
		@student = Student.find(params[:id])
	end

	def show
		@student = Student.find(params[:id])
	end

	def update
		student = Student.find(params[:id])
		student.update(student_params)
        #   Have to find a way to flash when updated with missing information
        flash[:notice] = t('notice.update')
		redirect_to students_path
	end

	def destroy
		Student.destroy(params[:id])
		redirect_to students_path
	end

	private	

	def student_params
		params.require(:student).permit(:first_name, :last_name, :age, :highest_completed_education)
		
	end
end

pams_panel_x/app/helpers/application_helper.rb
module ApplicationHelper
end

pams_panel_x/app/helpers/cohorts_helper.rb
module CohortsHelper
end

pams_panel_x/app/helpers/courses_helper.rb
module CoursesHelper
end

pams_panel_x/app/helpers/instructors_helper.rb
module InstructorsHelper
end

pams_panel_x/app/helpers/landing_helper.rb
module LandingHelper
end

pams_panel_x/app/helpers/students_cohorts_helper.rb
module StudentsCohortsHelper
end

pams_panel_x/app/helpers/students_helper.rb
module StudentsHelper
end

pams_panel_x/app/views/cohorts/_form.erb
<%= form_for  @cohort do |f| %>
		  <div>
		 	 <%= f.label :name %>
		 	 <%= f.text_field :name %>
		  </div>

		  <div>
		 	 <%= f.label :start_date %>
		 	 <%= f.text_field :start_date %>
		  </div>

		  <div>
		 	 <%= f.label :end_date %>
		 	 <%= f.text_field :end_date %>
		  </div>

		  <div>
		 	 <%= f.label :instructor_id %>
		 	 <%= f.select(:instructor_id, @instructors.map {|i| ["#{i.last_name}, #{i.first_name}", i.id]}) %>
		  </div>

		  <div>
		 	 <%= f.label :course_id %>
		 	 <%= f.select(:course_id, @courses.map {|c| [c.name, c.id]}) %>
		  </div>

		  <div>
		  	 <%= f.submit %>
		  </div>

<% end %>

pams_panel_x/app/views/cohorts/edit.erb
<h2> <%= t('edit.cohort_title') %> </h2>

      <%= render 'form'%>

pams_panel_x/app/views/cohorts/index.erb
<h2> Cohort Home Page</h2>

<h4>
  	<%= link_to 'Add A New Cohort to the Data Base', new_cohort_path %>
</h4>


<h3> List of Cohorts </h3>

   <% @cohorts.each do |cohort| %>

   <div> 
      Name: <%= cohort.name%>
   </div>

   <div> 
     Start Date : <%= cohort.start_date %>
   </div>

    <div> 
     End Date : <%= cohort.end_date %>
   </div>

   <div> 
     Instructor : <%= cohort.instructor_id%>
   </div>


  <div>
		<%= link_to 'Full Stats', cohort_path(cohort), 'data-disable-with': "Hold, please..." %>
		
	
		<%= link_to 'Edit', edit_cohort_path(cohort), 'data-disable-with': "Transferring now..." %>

    <%= link_to 'Remove', cohort_path(cohort), method: :delete, data: { confirm: 'Are you sure?' } %>


	</div>

	<br>

   <% end %>

pams_panel_x/app/views/cohorts/new.erb
<h2> Input a New Cohort </h2>

      <%= render 'form'%>

pams_panel_x/app/views/cohorts/show.erb
<h2> Cohort Detailed Information</h2>


<div>  
	Name: <%= @cohort.name %>
</div>

<div> 
	Start Date: <%= @cohort.start_date %> 
</div>

<div> 
	End Date: <%= @cohort.end_date %> 
</div>

<div> 
	Instructor: <%= @cohort.instructor_id %> 
</div>

pams_panel_x/app/views/courses/_form.erb
<%= form_for  @course do |f| %>
		  <div>
		 	 <%= f.label :name %>
		 	 <%= f.text_field :name %>
		  </div>

		  <div>
		 	 <%= f.label :total_in_class_hours %>
		 	 <%= f.text_field :total_in_class_hours %>
		  </div>

		  <div>
		  	 <%= f.submit %>
		  </div>

<% end %>

pams_panel_x/app/views/courses/edit.erb
<h2> <%= t('edit.courses_title') %> </h2>

      <%= render 'form'%>

pams_panel_x/app/views/courses/index.erb
<h2> Course Home Page</h2>

<h4>
  	<%= link_to 'Add A New Course to the Data Base', new_course_path %>
</h4>


<h3> List of Courses </h3>

   <% @courses.each do |course| %>

   <div> 
      Name: <%= course.name%>
   </div>

   <div> 
      Total Hours In Class: <%= course.total_in_class_hours %>
   </div>


  <div>
		<%= link_to 'Full Stats', course_path(course), 'data-disable-with': "Hold, please..." %>
		
	
		<%= link_to 'Edit', edit_course_path(course), 'data-disable-with': "Transferring now..." %>

    <%= link_to 'Remove', course_path(course), method: :delete, data: { confirm: 'Are you sure?' } %>


	</div>

	<br>

   <% end %>

pams_panel_x/app/views/courses/new.erb
<h2> Input a New Course </h2>

      <%= render 'form'%>

pams_panel_x/app/views/courses/show.erb
<h2> Course Detailed Information</h2>


<div>  Name: <%= @course.name %> </div>

<div> Total Hours In Class: <%= @course.total_hours_in_class %> </div>

pams_panel_x/app/views/instructors/_form.erb
<%= form_for  @instructor do |f| %>
		  <div>
		 	 <%= f.label :first_name %>
		 	 <%= f.text_field :first_name %>
		  </div>

		  <div>
		 	 <%= f.label :last_name %>
		 	 <%= f.text_field :last_name %>
		  </div>

		  <div>
		 	 <%= f.label :highest_completed_education%>
		 	 <%= f.select(:highest_completed_education, [ t("form.hs"), t("form.college") ,
		           t("form.masters"), t("form.phd" )]) %>
		 </div>

		 <div>
		 	 <%= f.label :age %>
		 	 <%= f.number_field :age %>
		 </div>

		 <div>
		 	 <%= f.label :salary %>
		 	 <%= f.text_field :salary %>
		 </div>


		 <div>
		  	<%= f.submit %>
		 </div>

<% end %>

pams_panel_x/app/views/instructors/edit.erb
<h2> <%= t('edit.instructor_title') %></h2>

<%= render 'form'%>

pams_panel_x/app/views/instructors/index.erb
<h2> Instructors Home Page</h2>

<h4>
  	<%= link_to 'Add A New Instructor to the Data Base', new_instructor_path %>
  	
</h4>


<h3> List of Instructors</h3>

   <% @instructors.each do |instructor| %>

   <div> Name: <%= instructor.last_name %>, <%= instructor.first_name %>
    </div>

    <div> Highest Education Completed: <%= instructor.highest_completed_education %>
    </div>

    <div>
		<%= link_to 'Full Stats', instructor_path(instructor), 'data-disable-with': "Hold, please..." %>
		
	
		<%= link_to 'Edit', edit_instructor_path(instructor), 'data-disable-with': "Transferring now..." %>

	


	</div>

	<br>



   <% end %>

pams_panel_x/app/views/instructors/new.erb
<h2> Input a New Instructor</h2>

<%= render 'form'%>

pams_panel_x/app/views/instructors/show.erb
<h2> Instuctor's Detailed Information</h2>


<div> First Name: <%= @instructor.first_name %> </div>

<div> Last Name: <%= @instructor.last_name %> </div>


<div> Highest Education Completed: <%= @instructor.highest_completed_education %> </div>


<div> Age: <%= @instructor.age %> </div>

<div> Salary: <%=number_to_currency( @instructor.salary )%></div>

pams_panel_x/app/views/landing/index.html.erb
<h1>  <%= t "landing.title" %> </h1>

  <h3> <%= t "landing.slogan" %>  </h3>
     

<ul>
	    <% if user_signed_in? %>
	<li>
		 <%= current_user.email %>
	</li>
	  <li>
	  	<%= link_to t('landing.sign_out'), destroy_user_session_path, method: :delete %>
	  </li>

	   <li>
	  	<%= link_to t('landing.edit'), edit_user_registration_path %>
	  </li>
	<% else %>
	    <li>
	    	<%= link_to t('landing.sign_in'), new_user_session_path %>
	    </li>
	    <li>
	    	<%= link_to t('landing.sign_up'), new_user_registration_path %>
	    </li>
	<% end %>
</ul>

pams_panel_x/app/views/students/_form.erb
<%= form_for  @student do |f| %>
		  <div>
		 	 <%= f.label :first_name, t('create.s_first_name') %>
		 	 <%= f.text_field :first_name %>
		  </div>

		  <div>

		 	 <%= f.label :last_name, t('create.s_last_name') %>
		 	 <%= f.text_field :last_name %>
		  </div>

		  <div>
		 	 <%= f.label :highest_completed_education, t('create.education') %>
		 	 <%= f.select(:highest_completed_education, [ t("form.hs"), t("form.college") ,
		           t("form.masters"), t("form.phd" )]) %>
		 </div>

		 <div>
		 	 <%= f.label :age, t('create.s_age') %>
		 	 <%= f.number_field :age %>
		 </div>

		


		 <div>
		  	<%= f.submit %>
		 </div>

<% end %>

pams_panel_x/app/views/students/edit.erb
<h2> <%= t('edit.student_title') %> </h2>

<%= render 'form' %>

pams_panel_x/app/views/students/index.erb
<h2> <%= t('home.s_title') %></h2>
 
<h4>
  	<%= link_to t('home.s_new_add') , new_student_path %>
  	
</h4>


<h3> <%= t('home.s_list') %></h3>
<div class="mb-4">
   <% @students.each do |student| %>
   <div class="mb-4 main-student">
    <div id="name-div">

   <div> <%= t('home.s_name') %>: <%= student.last_name %>, <%= student.first_name %>
    </div>
      </div>

    <div> Highest Education Completed: <%= t('home.s_education') %>
    </div>

    <div>
		<%= link_to t('home.s_full_stats'), student_path(student), 'data-disable-with': "Hold, please..." %>
		
	
		<%= link_to t('home.s_edit_button'), edit_student_path(student), 'data-disable-with': "Transferring now..." %>

    <%= link_to 'Remove', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %>

	


	</div>

	<br>


</div>
   <% end %>

</div>

pams_panel_x/app/views/students/new.erb
<h2> <%= t('new.s_title') %>  </h2>

<%= render 'form'%>

pams_panel_x/app/views/students/show.erb
<h2> Student's Detailed Information</h2>


<div> First Name: <%= @student.first_name %> </div>

<div> Last Name: <%= @student.last_name %> </div>


<div> Highest Education Completed: <%= @student.highest_completed_education %> </div>


<div> Age: <%= @student.age %> </div>