pams_panel_x/config/routes.rb
Rails.application.routes.draw do
 

     devise_for :users

 


  get 'landing/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
        root 'landing#index'
 scope	":locale" do
        resources :instructors do
		end

		resources :students do
		end

		resources :courses do
		end

		resources :cohorts do
		end

 end
end

pams_panel_x/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pams_panel_x/app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :instructor
  belongs_to :course
  validates :name, :start_date, :end_date,:course_id, :instructor_id, presence: true

end

pams_panel_x/app/models/course.rb
class Course < ApplicationRecord
	validates :name, :total_in_class_hours, presence: true
   validates :total_in_class_hours, numericality: { :greater_than => 0}
end

pams_panel_x/app/models/instructor.rb
class Instructor < ApplicationRecord
	validates :first_name, :last_name, :age, :salary, :highest_completed_education, presence: true
	validates :salary, numericality: { :greater_than => 0}
	validates :age, numericality: { :less_than => 150}

end

pams_panel_x/app/models/student.rb
class Student < ApplicationRecord
	validates :first_name, :last_name, :age, :highest_completed_education, presence: true
	validates :age, numericality: { :less_than => 150}
end

pams_panel_x/app/models/students_cohort.rb
class StudentsCohort < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

pams_panel_x/app/models/user.rb
class User < ApplicationRecord

 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

pams_panel_x/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_locale

	private

	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
		
	end

	def default_url_options
		{locale: I18n.locale}
		
	end
		
end

pams_panel_x/app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
    before_action :authenticate_user!
	def index
		@cohorts = Cohort.all	
	end

	def create
		Cohort.create(cohort_params)
		@instructors = Instructor.all
		@courses = Course.all

		flash[:notice] = "New Cohort Record created Successfully!"

		redirect_to  cohorts_path
	end

	def new
		@cohort = Cohort.new
		@instructors = Instructor.all
		@courses = Course.all
	end

	def edit
		@cohort = Cohort.find(params[:id])
		@instructors = Instructor.all
		@courses = Course.all
	end 

	def show
		@cohort = Cohort.find(params[:id])
	end

	def update
		cohort = Cohort.find(params[:id])
		cohort.update(cohort_params)

		@instructors = Instructor.all
		@courses = Course.all

		flash[:notice] = "Updated Successfully!"

		redirect_to cohorts_path
	end

	def destroy
		Cohort.destroy(params[:id])
		redirect_to cohorts_path
	end

	private	

	def cohort_params
		params.require(:cohort).permit(:name, :start_date, :end_date, :course_id, :instructor_id)
		
	end
end

pams_panel_x/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_user!
	def index
		@courses = Course.all	
	end

	def create
		@course = Course.create(course_params)
		if @course.valid?
		    flash[:notice] = "Success! New Course Record Made."
		     redirect_to courses_path
		 else
		 	flash[:notice] = "Missing Information."
		 	render :new
		 end

	def new
		@course = Course.new
	end

	def edit
		@course = Course.find(params[:id])
	end 

	def show
		@course = Course.find(params[:id])
	end

	def update
		course = Course.find(params[:id])
		course.update(course_params)
		flash[:notice] = "Updated Successfully!"

		redirect_to courses_path
	end

	def destroy
		Course.destroy(params[:id])
		redirect_to courses_path
	end

	private	

	def course_params
		params.require(:course).permit(:name, :total_in_class_hours)
		
	end
end
end

pams_panel_x/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	before_action :authenticate_user!
	def index
		@instructors = Instructor.all
	end


	def create
		@instructor = Instructor.create(instructor_params)

		if @instructor.valid?
		    flash[:notice] = "Success! New Instructor Record Made."
		     redirect_to instructors_path
		 else
		 	flash[:notice] = "Missing Information."
		 	render :new
		 end
	end

	def new
		@instructor = Instructor.new	
	end

	def edit
		@instructor = Instructor.find(params[:id])
	end

	def show
		@instructor = Instructor.find(params[:id])
	end

	def update
		instructor = Instructor.find(params[:id])
		instructor.update(instructor_params)
		flash[:notice] = "Record Updated Successfully!"
		
		redirect_to instructors_path
	end

	def destroy
		# find a way to hide instead of destroy teacher data.
		Instructor.destroy(params[:id])
		redirect_to instructors_path
	end

	def instructor_params
		params.require(:instructor).permit(:first_name, :last_name, :highest_completed_education, :age, :salary)
		
	end
end

pams_panel_x/app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

pams_panel_x/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!
	def index
		@students = Student.all.order(:last_name)
	end

	def create
		@student = Student.create(student_params)
        
        if @student.valid?
		    flash[:notice] = t('notice.new')
		     redirect_to students_path
		 else
		 	flash[:notice] = t('notice.failure')
		 	render :new
		 end
	end

	def new
		@student = Student.new
	end

	def edit
		@student = Student.find(params[:id])
	end

	def show
		@student = Student.find(params[:id])
	end

	def update
		student = Student.find(params[:id])
		student.update(student_params)
        #   Have to find a way to flash when updated with missing information
        flash[:notice] = t('notice.update')
		redirect_to students_path
	end

	def destroy
		Student.destroy(params[:id])
		redirect_to students_path
	end

	private	

	def student_params
		params.require(:student).permit(:first_name, :last_name, :age, :highest_completed_education)
		
	end
end

pams_panel_x/app/helpers/application_helper.rb
module ApplicationHelper
end

pams_panel_x/app/helpers/cohorts_helper.rb
module CohortsHelper
end

pams_panel_x/app/helpers/courses_helper.rb
module CoursesHelper
end

pams_panel_x/app/helpers/instructors_helper.rb
module InstructorsHelper
end

pams_panel_x/app/helpers/landing_helper.rb
module LandingHelper
end

pams_panel_x/app/helpers/students_cohorts_helper.rb
module StudentsCohortsHelper
end

pams_panel_x/app/helpers/students_helper.rb
module StudentsHelper
end

pams_panel_x/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PamsPanelX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Bungee+Shade|Open+Sans" rel="stylesheet"> 
  </head>
 


    <div class="wrapper">
     <nav>
      <div class="logo">  
        <i class="fa fa-rocket" aria-hidden="true"> </i>
       </div>
       <div class="menu-icon">
        <i class="fa fa-bars"></i>
       </div>
       
         <ul>
         
           <li> 
             <%= link_to t('navi.student'), students_url %>
           </li>
           <li>
             
             <%= link_to t('navi.instructor'), instructors_url %>
           </li>
           <li> 
               <%= link_to t('navi.cohort'), cohorts_url %>
           </li>
           <li>
             <%= link_to t('navi.courses'), courses_url %>
           </li>

             <li>
               
                  <% if user_signed_in? %>
                  <%= link_to t('landing.sign_out'), destroy_user_session_path, method: :delete %>
                     <% else %>
                  
                 <% end %>
             </li>

              <div class="dropdown">
                <button class="dropbtn"> <%= t('navi.lang') %>
                  <i class="fa fa-caret-down"></i>
                </button>
                <ul class="dropdown-content">
                 <li> 
                  <%= link_to "English", locale: "en" %>
                 </li>
                 <li>
                   <%= link_to "Spanish", locale: "es" %>
                 </li>
                </ul>
              </div>

         </ul>

       
     </nav>        
    </div>

    <div id="preloader"></div>
    

 <div class="inner_body"> 

 


    
    

   
<div id="notice_wrapper">
  <% if !flash[:notice].blank? %>
   <div class="notice">
   <%= flash[:notice] %>
 
   </div>
   <% end %>  
  
</div>
<%= yield %>


    <div class="footer">
         
  
             <%= link_to t('navi.student'), students_url %>
      
             
             <%= link_to t('navi.instructor'), instructors_url %>
        
               <%= link_to t('navi.cohort'), cohorts_url %>
           
             <%= link_to t('navi.courses'), courses_url %>
           

           
              </div>
         </ul>
      
    </div>


</div>
  </body>
</html>